name: CI

on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: mymindstorm/setup-emsdk@v11
      - uses: actions/cache@v3
        with:
          path: ~/.emscripten_cache
          key: ${{ runner.os }}-emscripten

      # Builds the project
      - run: |
          make wasm
          mv dist/TETRIS.html dist/index.html
          
      # Deploys dist folder to pages
      - uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: dist
          
